# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Ding Talk PR Notify'
description: 'A ding talk pr notify of GitHub actions.'
author: 'lijinke666'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true

#outputs:
#  result:
#    description: action result

runs:
  using: 'node12'
  main: 'dist/index.js'
